import { useState, useEffect, useRef, useCallback } from "react";

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// LEGAL & COMPLIANCE CONSTANTS
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
const LEGAL = {
  TOS_VERSION: "1.0.0",
  PRIVACY_VERSION: "1.0.0",
  MIN_AGE: 18,
  APP_NAME: "FuelPlan Pro",
  COMPANY: "FuelPlan Technologies",
  CONTACT_EMAIL: "legal@fuelplan.app",
  EFFECTIVE_DATE: "March 22, 2025",
  JURISDICTIONS: ["United States (CCPA/FTC)", "European Union (GDPR)", "United Kingdom (UK GDPR)", "Canada (PIPEDA)"],
  CLASSIFICATION: "General Wellness Application — Not a Medical Device",
  TERMS_OF_SERVICE: `TERMS OF SERVICE — FuelPlan Pro
Effective: March 22, 2025 · Version 1.0.0

1. NATURE OF SERVICE
FuelPlan Pro is a general wellness and nutrition guidance application. It provides AI-generated meal planning suggestions and general fitness nutrition information for healthy adults. It is NOT a medical service, healthcare provider, or medical device.

2. NOT MEDICAL ADVICE
ALL content, recommendations, meal plans, macro calculations, and AI responses are for GENERAL INFORMATIONAL AND WELLNESS PURPOSES ONLY. Nothing in this app constitutes medical advice, diagnosis, treatment, or a substitute for professional medical care. Always consult a qualified physician, registered dietitian, or licensed healthcare professional before making significant dietary changes, especially if you have any medical condition, allergy, are pregnant, breastfeeding, or taking medication.

3. AI-GENERATED CONTENT LIMITATIONS
Content is generated by artificial intelligence and may contain errors or inaccuracies. AI systems can generate plausible-sounding but incorrect information. You should independently verify any critical nutritional or health information with a qualified professional.

4. SCOPE LIMITATIONS
This app is architecturally designed to refuse to: (a) diagnose any medical condition; (b) recommend medications or supplements as treatments; (c) provide advice that could replace a licensed dietitian for therapeutic nutrition; (d) process your data for any purpose other than generating your personal wellness content.

5. ELIGIBILITY
You must be at least 18 years of age to use this app.

6. HEALTH REPORTS
If you upload a health report or lab results, this data is: processed in your current browser session only, never stored on any server, discarded when your session ends, and used solely to inform general wellness suggestions — not for clinical analysis.

7. LIMITATION OF LIABILITY
TO THE MAXIMUM EXTENT PERMITTED BY LAW, FuelPlan Technologies shall not be liable for any damages arising from your use of or reliance on this app.

8. GOVERNING LAW
These terms are governed by the laws of the State of Delaware, United States.`,

  PRIVACY_POLICY: `PRIVACY POLICY — FuelPlan Pro
Effective: March 22, 2025 · Version 1.0.0

SUMMARY: Your personal data never leaves your device. We do not have servers that store your information.

1. DATA WE COLLECT AND WHERE IT LIVES
a) Profile Data (stored in your browser's localStorage ONLY):
— Display name (for UI personalization only)
— Age bracket (e.g., "25–34") — not your exact age
— BMI category (e.g., "normal") — not your exact weight or height
— Biological sex, cultural heritage category, fitness goal, budget preference

b) Health Reports (NEVER stored anywhere):
— Processed temporarily in-session only, immediately discarded.

c) Location (NEVER stored):
— City name only used for grocery deal searches, never stored.

2. DATA WE NEVER COLLECT
— Your exact age, weight, or height
— Your full name, IP address, GPS coordinates
— Health report content (after session ends)

3. YOUR RIGHTS
GDPR / UK GDPR / CCPA / PIPEDA: You may delete all locally stored data at any time via the Privacy tab → "Delete All My Data."

4. CONTACT
For privacy questions: legal@fuelplan.app`,
};

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// COMPLIANCE ENGINE
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
const Compliance = {
  recordConsent: (ageConfirmed) => {
    const record = {
      tosVersion: LEGAL.TOS_VERSION,
      privacyVersion: LEGAL.PRIVACY_VERSION,
      timestamp: new Date().toISOString(),
      ageConfirmed,
      jurisdiction: Intl.DateTimeFormat().resolvedOptions().timeZone || "unknown",
      method: "explicit_checkbox_and_button",
    };
    localStorage.setItem("fp_consent_record", JSON.stringify(record));
    localStorage.setItem("fp_tos_version", LEGAL.TOS_VERSION);
    localStorage.setItem("fp_privacy_version", LEGAL.PRIVACY_VERSION);
    return record;
  },
  hasValidConsent: () => {
    const storedTos = localStorage.getItem("fp_tos_version");
    const storedPrv = localStorage.getItem("fp_privacy_version");
    return storedTos === LEGAL.TOS_VERSION && storedPrv === LEGAL.PRIVACY_VERSION;
  },
  revokeConsent: () => {
    ["fp_consent_record","fp_tos_version","fp_privacy_version","fp_profile_raw","fp_profile_safe",
     "fp_mealplan","fp_macros","fp_audit","fp_analytics"].forEach(k => localStorage.removeItem(k));
  },
  auditLog: (action, detail = "") => {
    try {
      const log = JSON.parse(localStorage.getItem("fp_audit") || "[]");
      log.push({ ts: new Date().toISOString(), action, detail: detail.slice(0, 100) });
      if (log.length > 50) log.splice(0, log.length - 50);
      localStorage.setItem("fp_audit", JSON.stringify(log));
    } catch {}
  },
  getAuditLog: () => { try { return JSON.parse(localStorage.getItem("fp_audit") || "[]"); } catch { return []; } },
  getConsentRecord: () => { try { return JSON.parse(localStorage.getItem("fp_consent_record") || "null"); } catch { return null; } },
};

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// SAFETY ENGINE
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
const Safety = {
  SYSTEM_PREAMBLE: `You are FuelCoach, a general wellness AI assistant for FuelPlan Pro.
LEGAL CLASSIFICATION: This app is a general wellness tool, NOT a medical device or healthcare service.
ABSOLUTE RULES — YOU MUST FOLLOW THESE WITHOUT EXCEPTION:
1. NEVER diagnose any medical condition, disease, or disorder.
2. NEVER recommend specific medications, supplements as treatments, or dosages.
3. NEVER suggest caloric intake below 1,200 calories/day for any reason.
4. NEVER provide advice that a licensed dietitian would be legally required to give.
5. ALWAYS recommend consulting a qualified physician or registered dietitian for medical conditions.
6. If a user describes a medical emergency, IMMEDIATELY direct them to call emergency services (911 in US).
7. If you detect signs of disordered eating, respond with compassion and provide NEDA Helpline: 1-800-931-2237.
8. Flag uncertainty explicitly — if unsure, say so and recommend professional consultation.
9. Do NOT reproduce exact personal identifiers in responses.
10. Stay within general wellness/fitness nutrition scope — redirect clinical questions.
11. Frame all content as general guidance, not personalized medical advice.
12. Privacy: do not encourage users to share more personal data than necessary.`,

  validateMacros: (macros, weightKg = 70) => {
    const warnings = []; const flags = [];
    const w = parseFloat(weightKg) || 70;
    if (macros.calories < 1200) { flags.push("CRITICAL_LOW_CALORIES"); warnings.push({ level: "error", msg: "⚠️ Calorie target below 1,200 — adjusted to minimum safe threshold. Please consult a registered dietitian before restricting below this level." }); macros.calories = 1200; }
    if (macros.calories > 5000) { flags.push("HIGH_CALORIES"); warnings.push({ level: "warning", msg: "Calorie target is unusually high. Verify this is appropriate for your activity level with a sports dietitian." }); }
    if (macros.protein_g > 3.5 * w) { flags.push("EXCESS_PROTEIN"); warnings.push({ level: "warning", msg: "Protein target exceeds 3.5g/kg body weight. Very high protein intake may stress kidneys — discuss with your doctor." }); }
    if (macros.fat_g < 20) { flags.push("VERY_LOW_FAT"); warnings.push({ level: "warning", msg: "Fat below 20g/day may impair absorption of fat-soluble vitamins (A, D, E, K)." }); }
    if (macros.carbs_g < 50) { flags.push("LOW_CARB"); warnings.push({ level: "info", msg: "Very low carbohydrate intake. If you have diabetes or take medication, discuss this plan with your doctor first." }); }
    Compliance.auditLog("macro_validation", `flags:${flags.join(",")}`);
    return { macros, warnings, flags };
  },

  screenMessage: (text) => {
    const t = text.toLowerCase();
    if (["chest pain","can't breathe","allergic reaction","severe pain","unconscious","overdose","stroke","heart attack"].some(k => t.includes(k))) return { type: "emergency", block: true };
    if (["diagnose me","do i have","am i sick","is this cancer","is this diabetes","prescribe","what medication"].some(k => t.includes(k))) return { type: "diagnosis", block: false };
    if (["how little can i eat","starve","not eat for","purge","laxative to lose","make myself sick"].some(k => t.includes(k))) return { type: "ed_risk", block: false };
    if (["my kid","my son","my daughter","years old","toddler","baby","infant"].some(k => t.includes(k))) return { type: "minor_mention", block: false };
    return { type: "safe", block: false };
  },
};

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// PRIVACY ENGINE
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
const Privacy = {
  anonymize: (profile) => ({
    ageBracket: !profile.age ? "unknown" : profile.age < 25 ? "18-24" : profile.age < 35 ? "25-34" : profile.age < 45 ? "35-44" : profile.age < 55 ? "45-54" : "55+",
    bmiCategory: (() => { const b = profile.weight / ((profile.height / 100) ** 2); return isNaN(b) ? "unknown" : b < 18.5 ? "underweight" : b < 25 ? "normal" : b < 30 ? "overweight" : "obese"; })(),
    gender: profile.gender,
    ethnicity: profile.ethnicity,
    goal: profile.goal,
    budget: profile.budget,
    displayName: profile.name?.trim().split(" ")[0] || "User",
  }),
  save: (profile) => {
    const safe = Privacy.anonymize(profile);
    localStorage.setItem("fp_profile_safe", JSON.stringify({ ...safe, savedAt: new Date().toISOString() }));
    localStorage.setItem("fp_profile_raw", JSON.stringify({ age: profile.age, weight: profile.weight, height: profile.height }));
    Compliance.auditLog("profile_saved", `goal:${profile.goal},heritage:${profile.ethnicity}`);
    return safe;
  },
  load: () => {
    try {
      const safe = JSON.parse(localStorage.getItem("fp_profile_safe") || "null");
      const raw = JSON.parse(localStorage.getItem("fp_profile_raw") || "null");
      return safe ? { ...safe, ...(raw || {}) } : null;
    } catch { return null; }
  },
  buildAPIContext: (profile, macros) => ({
    ageBracket: profile.ageBracket || Privacy.anonymize(profile).ageBracket,
    bmiCategory: profile.bmiCategory || Privacy.anonymize(profile).bmiCategory,
    gender: profile.gender,
    ethnicity: profile.ethnicity,
    goal: profile.goal,
    budget: profile.budget,
    macros: macros ? `${macros.calories}cal | ${macros.protein_g}g P | ${macros.carbs_g}g C | ${macros.fat_g}g F` : null,
  }),
  saveData: (key, data) => { try { localStorage.setItem(key, JSON.stringify(data)); } catch {} },
  loadData: (key) => { try { return JSON.parse(localStorage.getItem(key) || "null"); } catch { return null; } },
  recordAnalytic: (event, value) => {
    try {
      const store = JSON.parse(localStorage.getItem("fp_analytics") || "{}");
      store[`${event}::${value}`] = (store[`${event}::${value}`] || 0) + 1;
      localStorage.setItem("fp_analytics", JSON.stringify(store));
    } catch {}
  },
  getAnalytics: () => { try { return JSON.parse(localStorage.getItem("fp_analytics") || "{}"); } catch { return {}; } },
};

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// SECURE CLAUDE API — Calls /api/claude proxy (API key stays server-side)
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
const callClaude = async (messages, extraSystem = "", useSearch = false) => {
  const body = {
    model: "claude-sonnet-4-20250514",
    max_tokens: 1000,
    system: Safety.SYSTEM_PREAMBLE + (extraSystem ? "\n\n" + extraSystem : ""),
    messages,
    ...(useSearch ? { tools: [{ type: "web_search_20250305", name: "web_search" }] } : {}),
  };
  // ✅ SECURE: calls our own backend proxy, not Anthropic directly
  const res = await fetch("/api/claude", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body),
  });
  const data = await res.json();
  if (data.error) throw new Error(data.error);
  return data.content?.map(b => b.text || "").filter(Boolean).join("\n") || "";
};

const callJSON = async (messages, extraSystem = "") => {
  const t = await callClaude(messages, extraSystem);
  try { const m = t.replace(/```json|```/g, "").trim().match(/\{[\s\S]*\}|\[[\s\S]*\]/); return m ? JSON.parse(m[0]) : null; } catch { return null; }
};

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// DATA
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
const ETHNICITIES = [
  { id: "west-african", label: "West African", emoji: "🌍", staples: ["plantain","yam","egusi","black-eyed peas","tilapia","moringa","palm oil"] },
  { id: "east-asian", label: "East Asian", emoji: "🍜", staples: ["brown rice","tofu","edamame","bok choy","miso","salmon","shiitake"] },
  { id: "south-asian", label: "South Asian", emoji: "🍛", staples: ["lentils","chickpeas","turmeric","paneer","basmati rice","fenugreek"] },
  { id: "mediterranean", label: "Mediterranean", emoji: "🫒", staples: ["olive oil","feta","hummus","quinoa","sardines","eggplant","pomegranate"] },
  { id: "latin-american", label: "Latin American", emoji: "🌮", staples: ["black beans","corn","avocado","sweet potato","cilantro","lean beef"] },
  { id: "middle-eastern", label: "Middle Eastern", emoji: "🧆", staples: ["tahini","za'atar","bulgur","lamb","labneh","sumac","freekeh"] },
  { id: "caribbean", label: "Caribbean", emoji: "🌴", staples: ["coconut","callaloo","jerk seasoning","breadfruit","saltfish","ackee"] },
  { id: "eastern-european", label: "Eastern European", emoji: "🥗", staples: ["buckwheat","kefir","beets","rye bread","herring","sauerkraut"] },
];

const GOALS = ["Weight Loss", "Muscle Gain", "Maintenance", "Athletic Performance", "Heart Health"];
const G = "#00e5a0", A = "#ffb84d", B = "#4d9fff", R = "#ff6b6b", P = "#c77dff";

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// UI COMPONENTS
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
const css = `
@import url('https://fonts.googleapis.com/css2?family=Syne:wght@600;700;800&family=DM+Sans:wght@300;400;500;600&display=swap');
@keyframes bounce { 0%,80%,100%{transform:translateY(0)} 40%{transform:translateY(-8px)} }
@keyframes fadeUp { from{opacity:0;transform:translateY(14px)} to{opacity:1;transform:translateY(0)} }
@keyframes fadeIn { from{opacity:0} to{opacity:1} }
@keyframes slideUp { from{opacity:0;transform:translateY(36px)} to{opacity:1;transform:translateY(0)} }
@keyframes pulse { 0%,100%{box-shadow:0 0 0 0 ${G}55} 60%{box-shadow:0 0 0 14px transparent} }
* { box-sizing:border-box; margin:0; padding:0; }
body { background:#07080f; color:#eef0f5; font-family:'DM Sans',sans-serif; }
::-webkit-scrollbar{width:4px} ::-webkit-scrollbar-thumb{background:rgba(255,255,255,.12);border-radius:4px}
input,textarea{outline:none;} a{color:${B};}
`;

function Pill({ children, active, onClick, color = G }) {
  return <button onClick={onClick} style={{ padding: "8px 16px", borderRadius: 30, border: `1px solid ${active ? color : "rgba(255,255,255,.1)"}`, background: active ? `${color}18` : "transparent", color: active ? color : "rgba(255,255,255,.5)", fontFamily: "'DM Sans',sans-serif", fontSize: 13, fontWeight: active ? 600 : 400, cursor: "pointer", transition: "all .2s", whiteSpace: "nowrap" }}>{children}</button>;
}

function Card({ children, style = {}, glow }) {
  return <div style={{ background: "rgba(255,255,255,.03)", border: "1px solid rgba(255,255,255,.08)", borderRadius: 18, padding: 20, boxShadow: glow ? `0 0 28px ${glow}20` : "none", ...style }}>{children}</div>;
}

function Tag({ children, color = G }) {
  return <span style={{ fontSize: 10, fontWeight: 700, letterSpacing: 1.5, textTransform: "uppercase", background: `${color}18`, color, border: `1px solid ${color}30`, padding: "3px 9px", borderRadius: 20 }}>{children}</span>;
}

function Spinner({ label = "Processing…" }) {
  return <div style={{ display: "flex", flexDirection: "column", alignItems: "center", gap: 14, padding: "40px 0" }}><div style={{ display: "flex", gap: 6 }}>{[0, 1, 2].map(i => <div key={i} style={{ width: 8, height: 8, borderRadius: "50%", background: G, animation: `bounce 1.2s ${i * .2}s infinite ease-in-out` }} />)}</div><div style={{ fontSize: 11, color: "rgba(255,255,255,.4)", letterSpacing: 2, textTransform: "uppercase" }}>{label}</div></div>;
}

function SafetyBanner({ warnings = [] }) {
  if (!warnings.length) return null;
  return <div style={{ marginBottom: 16 }}>{warnings.map((w, i) => <div key={i} style={{ display: "flex", gap: 10, padding: "11px 14px", borderRadius: 12, marginBottom: 8, background: w.level === "error" ? "rgba(255,107,107,.08)" : w.level === "warning" ? "rgba(255,184,77,.07)" : "rgba(77,159,255,.07)", border: `1px solid ${w.level === "error" ? R + "35" : w.level === "warning" ? A + "35" : B + "35"}` }}><span style={{ fontSize: 15, flexShrink: 0 }}>{w.level === "error" ? "🚨" : "⚠️"}</span><span style={{ fontSize: 12, color: "rgba(255,255,255,.75)", lineHeight: 1.6 }}>{w.msg}</span></div>)}</div>;
}

function MedDisclaimer({ compact }) {
  if (compact) return <div style={{ fontSize: 11, color: "rgba(255,255,255,.28)", textAlign: "center", padding: "8px 12px", lineHeight: 1.5 }}>⚕️ General wellness guidance only — not medical advice. Consult a qualified healthcare professional before making dietary changes.</div>;
  return <div style={{ background: "rgba(77,159,255,.05)", border: "1px solid rgba(77,159,255,.18)", borderRadius: 14, padding: "15px 18px", marginBottom: 18 }}><div style={{ fontSize: 10, fontWeight: 700, letterSpacing: 2, textTransform: "uppercase", color: B, marginBottom: 8 }}>⚕️ Important Health Notice</div><div style={{ fontSize: 12, color: "rgba(255,255,255,.6)", lineHeight: 1.75 }}>FuelPlan Pro provides <strong style={{ color: "rgba(255,255,255,.85)" }}>general wellness guidance only</strong> and is not a medical service, medical device, or substitute for professional healthcare. Always consult a qualified physician or registered dietitian. <span style={{ color: B, fontWeight: 600 }}>Classified as a General Wellness Application under applicable digital health regulations.</span></div></div>;
}

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// CONSENT SCREEN
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
function ConsentScreen({ onAccept, onDecline }) {
  const [tab, setTab] = useState("overview");
  const [checked, setChecked] = useState({ age: false, tos: false, privacy: false, medical: false });
  const allChecked = Object.values(checked).every(Boolean);

  return (
    <div style={{ position: "fixed", inset: 0, background: "#07080f", zIndex: 200, display: "flex", flexDirection: "column", animation: "fadeIn .3s" }}>
      <style>{css}</style>
      <div style={{ padding: "20px 20px 0", borderBottom: "1px solid rgba(255,255,255,.07)", background: "rgba(7,8,15,.98)", position: "sticky", top: 0, zIndex: 10 }}>
        <div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 16 }}>
          <div style={{ width: 40, height: 40, borderRadius: 12, background: `${G}18`, border: `1px solid ${G}30`, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 20 }}>⚡</div>
          <div>
            <div style={{ fontFamily: "'Syne',sans-serif", fontSize: 18, fontWeight: 800 }}>Before You Begin</div>
            <div style={{ fontSize: 12, color: "rgba(255,255,255,.4)" }}>Please review and accept our terms — v{LEGAL.TOS_VERSION}</div>
          </div>
        </div>
        <div style={{ display: "flex", gap: 4, paddingBottom: 1 }}>
          {[["overview", "Overview"], ["tos", "Terms"], ["privacy", "Privacy"], ["legal", "Legal"]].map(([id, label]) => (
            <button key={id} onClick={() => setTab(id)} style={{ flex: 1, padding: "8px 4px", border: "none", background: tab === id ? G : "transparent", color: tab === id ? "#07080f" : "rgba(255,255,255,.4)", fontFamily: "'DM Sans',sans-serif", fontSize: 12, fontWeight: 700, cursor: "pointer", borderRadius: "8px 8px 0 0", transition: "all .2s" }}>{label}</button>
          ))}
        </div>
      </div>

      <div style={{ flex: 1, overflowY: "auto", padding: "20px" }}>
        {tab === "overview" && (
          <div>
            <div style={{ fontFamily: "'Syne',sans-serif", fontSize: 22, fontWeight: 800, marginBottom: 6 }}>Your Rights & Our Commitments</div>
            <div style={{ fontSize: 13, color: "rgba(255,255,255,.5)", marginBottom: 20, lineHeight: 1.6 }}>FuelPlan Pro is built on privacy by design and legal compliance.</div>
            {[
              [G, "🔒", "Data stays on your device", "All profile data, meal plans, and preferences are stored only in your browser. We have no servers holding your personal information."],
              [G, "🏥", "Health reports are session-only", "Uploaded health documents are processed temporarily and discarded immediately. They are never stored or shared."],
              [A, "⚕️", "Not a medical service", "This app provides general wellness guidance. It cannot diagnose, treat, or replace your doctor or registered dietitian."],
              [B, "🤖", "AI-generated content", "Meal plans and recommendations are AI-generated and may contain errors. Always verify critical health information with a professional."],
              [P, "🌍", "Multi-jurisdiction compliance", "Designed to comply with GDPR (EU), CCPA (California), PIPEDA (Canada), and UK GDPR standards."],
            ].map(([color, icon, title, desc]) => (
              <div key={title} style={{ display: "flex", gap: 14, marginBottom: 14, padding: "14px 16px", background: "rgba(255,255,255,.03)", border: `1px solid ${color}18`, borderRadius: 14 }}>
                <span style={{ fontSize: 20, flexShrink: 0 }}>{icon}</span>
                <div><div style={{ fontWeight: 600, fontSize: 14, color, marginBottom: 4 }}>{title}</div><div style={{ fontSize: 12, color: "rgba(255,255,255,.5)", lineHeight: 1.6 }}>{desc}</div></div>
              </div>
            ))}
          </div>
        )}
        {tab === "tos" && <div style={{ background: "rgba(255,255,255,.02)", borderRadius: 14, padding: "18px", border: "1px solid rgba(255,255,255,.07)" }}><pre style={{ fontFamily: "'DM Sans',sans-serif", fontSize: 12, color: "rgba(255,255,255,.65)", lineHeight: 1.8, whiteSpace: "pre-wrap" }}>{LEGAL.TERMS_OF_SERVICE}</pre></div>}
        {tab === "privacy" && <div style={{ background: "rgba(255,255,255,.02)", borderRadius: 14, padding: "18px", border: "1px solid rgba(255,255,255,.07)" }}><pre style={{ fontFamily: "'DM Sans',sans-serif", fontSize: 12, color: "rgba(255,255,255,.65)", lineHeight: 1.8, whiteSpace: "pre-wrap" }}>{LEGAL.PRIVACY_POLICY}</pre></div>}
        {tab === "legal" && (
          <div>
            <Card style={{ marginBottom: 12 }}>
              <div style={{ fontSize: 11, fontWeight: 700, letterSpacing: 2, textTransform: "uppercase", color: "rgba(255,255,255,.35)", marginBottom: 12 }}>App Classification</div>
              <div style={{ fontSize: 14, fontWeight: 600, color: G, marginBottom: 8 }}>{LEGAL.CLASSIFICATION}</div>
              <div style={{ fontSize: 12, color: "rgba(255,255,255,.5)", lineHeight: 1.7 }}>This app does not meet the definition of a Software as a Medical Device (SaMD) under FDA guidance. It provides only general wellness functions, not clinical decision support.</div>
            </Card>
            <Card>
              <div style={{ fontSize: 11, fontWeight: 700, letterSpacing: 2, textTransform: "uppercase", color: "rgba(255,255,255,.35)", marginBottom: 10 }}>Regulatory Compliance</div>
              {LEGAL.JURISDICTIONS.map(j => <div key={j} style={{ fontSize: 13, color: "rgba(255,255,255,.6)", padding: "6px 0", borderBottom: "1px solid rgba(255,255,255,.05)" }}>✓ {j}</div>)}
            </Card>
          </div>
        )}
      </div>

      <div style={{ padding: "16px 20px", borderTop: "1px solid rgba(255,255,255,.07)", background: "rgba(7,8,15,.98)" }}>
        {[
          ["age", `I confirm I am ${LEGAL.MIN_AGE} years of age or older`],
          ["tos", "I have read and accept the Terms of Service"],
          ["privacy", "I have read and accept the Privacy Policy"],
          ["medical", "I understand this app provides general wellness guidance only, not medical advice"],
        ].map(([key, label]) => (
          <div key={key} onClick={() => setChecked(c => ({ ...c, [key]: !c[key] }))} style={{ display: "flex", alignItems: "flex-start", gap: 12, marginBottom: 10, cursor: "pointer" }}>
            <div style={{ width: 20, height: 20, borderRadius: 5, border: `2px solid ${checked[key] ? G : "rgba(255,255,255,.2)"}`, background: checked[key] ? G : "transparent", flexShrink: 0, display: "flex", alignItems: "center", justifyContent: "center", marginTop: 1, transition: "all .2s" }}>
              {checked[key] && <span style={{ color: "#07080f", fontSize: 11, fontWeight: 800 }}>✓</span>}
            </div>
            <span style={{ fontSize: 12, color: "rgba(255,255,255,.65)", lineHeight: 1.5 }}>{label}</span>
          </div>
        ))}
        <div style={{ display: "flex", gap: 10, marginTop: 14 }}>
          <button onClick={onDecline} style={{ flex: 1, padding: "13px", borderRadius: 12, border: "1px solid rgba(255,255,255,.1)", background: "transparent", color: "rgba(255,255,255,.5)", fontFamily: "'DM Sans',sans-serif", fontSize: 14, fontWeight: 600, cursor: "pointer" }}>Decline</button>
          <button onClick={() => allChecked && onAccept()} style={{ flex: 2, padding: "13px", borderRadius: 12, border: "none", background: allChecked ? G : "rgba(255,255,255,.08)", color: allChecked ? "#07080f" : "rgba(255,255,255,.25)", fontFamily: "'Syne',sans-serif", fontSize: 15, fontWeight: 700, cursor: allChecked ? "pointer" : "not-allowed", transition: "all .2s" }}>
            {allChecked ? "I Agree — Continue →" : "Check all boxes to continue"}
          </button>
        </div>
        <MedDisclaimer compact />
      </div>
    </div>
  );
}

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// COMPLIANCE PANEL
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
function CompliancePanel({ onDeleteData }) {
  const consent = Compliance.getConsentRecord();
  const audit = Compliance.getAuditLog();
  const analytics = Privacy.getAnalytics();
  const [activeSection, setSection] = useState("rights");

  return (
    <div style={{ padding: "18px 14px", maxWidth: 640, margin: "0 auto" }}>
      <div style={{ fontFamily: "'Syne',sans-serif", fontSize: 24, fontWeight: 800, marginBottom: 4 }}>Privacy & Compliance</div>
      <div style={{ fontSize: 13, color: "rgba(255,255,255,.4)", marginBottom: 20 }}>Full transparency into what we store and your legal rights</div>
      <div style={{ display: "flex", gap: 4, marginBottom: 20, overflowX: "auto" }}>
        {[["rights", "Your Rights"], ["inventory", "Data Inventory"], ["audit", "Audit Log"], ["analytics", "Analytics"]].map(([id, label]) => (
          <button key={id} onClick={() => setSection(id)} style={{ flexShrink: 0, padding: "8px 14px", borderRadius: 8, border: "none", background: activeSection === id ? G : "rgba(255,255,255,.05)", color: activeSection === id ? "#07080f" : "rgba(255,255,255,.45)", fontFamily: "'DM Sans',sans-serif", fontSize: 12, fontWeight: 700, cursor: "pointer" }}>{label}</button>
        ))}
      </div>

      {activeSection === "rights" && (
        <>
          {consent && (
            <Card style={{ marginBottom: 14, background: `${G}06`, borderColor: `${G}20` }}>
              <div style={{ fontSize: 11, fontWeight: 700, letterSpacing: 2, textTransform: "uppercase", color: G, marginBottom: 10 }}>✓ Consent Record</div>
              {[["Accepted", new Date(consent.timestamp).toLocaleString()], ["ToS Version", consent.tosVersion], ["Privacy Version", consent.privacyVersion], ["Method", consent.method]].map(([k, v]) => (
                <div key={k} style={{ display: "flex", justifyContent: "space-between", fontSize: 12, padding: "6px 0", borderBottom: "1px solid rgba(255,255,255,.05)" }}>
                  <span style={{ color: "rgba(255,255,255,.4)" }}>{k}</span><span style={{ color: "rgba(255,255,255,.8)" }}>{v}</span>
                </div>
              ))}
            </Card>
          )}
          <button onClick={onDeleteData} style={{ width: "100%", padding: "13px", borderRadius: 12, border: `1px solid ${R}40`, background: `${R}08`, color: R, fontFamily: "'DM Sans',sans-serif", fontSize: 14, fontWeight: 700, cursor: "pointer", marginBottom: 8 }}>🗑️ Delete All My Data (GDPR / CCPA Right to Erasure)</button>
          <div style={{ fontSize: 11, color: "rgba(255,255,255,.3)", textAlign: "center", lineHeight: 1.5 }}>This permanently removes all locally stored data and revokes consent.</div>
        </>
      )}
      {activeSection === "audit" && (
        <Card>
          <div style={{ fontSize: 11, fontWeight: 700, letterSpacing: 2, textTransform: "uppercase", color: "rgba(255,255,255,.35)", marginBottom: 12 }}>Activity Audit Log (Local)</div>
          {audit.length === 0
            ? <div style={{ fontSize: 13, color: "rgba(255,255,255,.3)", textAlign: "center", padding: "20px 0" }}>No audit entries yet</div>
            : [...audit].reverse().map((entry, i) => (
              <div key={i} style={{ padding: "9px 0", borderBottom: "1px solid rgba(255,255,255,.05)" }}>
                <div style={{ display: "flex", justifyContent: "space-between", marginBottom: 3 }}>
                  <span style={{ fontSize: 12, fontWeight: 600, color: G }}>{entry.action}</span>
                  <span style={{ fontSize: 11, color: "rgba(255,255,255,.3)" }}>{new Date(entry.ts).toLocaleString()}</span>
                </div>
                {entry.detail && <div style={{ fontSize: 11, color: "rgba(255,255,255,.4)" }}>{entry.detail}</div>}
              </div>
            ))}
        </Card>
      )}
      {activeSection === "inventory" && (
        <Card>
          <div style={{ fontSize: 11, fontWeight: 700, letterSpacing: 2, textTransform: "uppercase", color: "rgba(255,255,255,.35)", marginBottom: 14 }}>Complete Data Inventory</div>
          {[
            ["Display Name", "localStorage", "First name only", G],
            ["Age Bracket", "localStorage", "e.g. '25–34' — not exact age", G],
            ["BMI Category", "localStorage", "e.g. 'normal' — not exact weight", G],
            ["Meal Plan", "localStorage", "AI-generated — no PII", G],
            ["Health Report", "NOT STORED", "Session-only, immediately discarded", R],
            ["GPS Coordinates", "NOT STORED", "Never collected", R],
            ["Full Name", "NOT STORED", "Never collected", R],
            ["IP Address", "NOT STORED", "Never collected", R],
          ].map(([field, location, note, color]) => (
            <div key={field} style={{ padding: "10px 0", borderBottom: "1px solid rgba(255,255,255,.05)" }}>
              <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 3 }}>
                <span style={{ fontSize: 13, fontWeight: 600 }}>{field}</span>
                <Tag color={color}>{location}</Tag>
              </div>
              <div style={{ fontSize: 11, color: "rgba(255,255,255,.4)" }}>{note}</div>
            </div>
          ))}
        </Card>
      )}
      {activeSection === "analytics" && (
        <Card>
          <div style={{ fontSize: 11, fontWeight: 700, letterSpacing: 2, textTransform: "uppercase", color: "rgba(255,255,255,.35)", marginBottom: 14 }}>Aggregate Signals (This Device)</div>
          {Object.keys(analytics).length === 0
            ? <div style={{ fontSize: 13, color: "rgba(255,255,255,.3)", textAlign: "center", padding: "16px 0" }}>No analytics recorded yet</div>
            : Object.entries(analytics).map(([key, count]) => (
              <div key={key} style={{ display: "flex", justifyContent: "space-between", fontSize: 13, padding: "7px 0", borderBottom: "1px solid rgba(255,255,255,.05)" }}>
                <span style={{ color: "rgba(255,255,255,.6)" }}>{key}</span><span style={{ color: G, fontWeight: 600 }}>{count}</span>
              </div>
            ))}
        </Card>
      )}
    </div>
  );
}

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// CHAT BUBBLE
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
function ChatBubble({ msg, onChip }) {
  const isUser = msg.role === "user";
  return (
    <div style={{ display: "flex", justifyContent: isUser ? "flex-end" : "flex-start", marginBottom: 10 }}>
      {!isUser && <div style={{ width: 30, height: 30, borderRadius: "50%", background: `${G}20`, border: `1px solid ${G}40`, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 14, flexShrink: 0, marginRight: 8, marginTop: 2 }}>⚡</div>}
      <div style={{ maxWidth: "80%", padding: "11px 15px", borderRadius: isUser ? "16px 16px 4px 16px" : "4px 16px 16px 16px", background: isUser ? `${G}1a` : "rgba(255,255,255,.05)", border: `1px solid ${isUser ? G + "35" : "rgba(255,255,255,.09)"}`, fontSize: 13, lineHeight: 1.7, color: "rgba(255,255,255,.85)", whiteSpace: "pre-wrap" }}>
        {msg.content}
        {msg.type === "emergency" && <div style={{ marginTop: 10, padding: "10px 12px", background: "rgba(255,107,107,.12)", border: "1px solid rgba(255,107,107,.3)", borderRadius: 10, fontSize: 12, color: R, fontWeight: 600 }}>🚨 Call 911 (US) or your local emergency number immediately.</div>}
        {msg.type === "ed_risk" && <div style={{ marginTop: 10, padding: "10px 12px", background: "rgba(255,184,77,.08)", border: "1px solid rgba(255,184,77,.25)", borderRadius: 10, fontSize: 12, color: A }}>💛 NEDA Helpline: 1-800-931-2237 · Text "NEDA" to 741741</div>}
        {msg.chips?.length > 0 && <div style={{ display: "flex", flexWrap: "wrap", gap: 6, marginTop: 10 }}>{msg.chips.map((c, i) => <span key={i} onClick={() => onChip?.(c)} style={{ fontSize: 11, background: `${B}18`, border: `1px solid ${B}30`, color: B, padding: "4px 10px", borderRadius: 20, cursor: "pointer", fontWeight: 600 }}>{c}</span>)}</div>}
        {!isUser && <div style={{ fontSize: 10, color: "rgba(255,255,255,.2)", marginTop: 8 }}>AI-generated · Not medical advice</div>}
      </div>
    </div>
  );
}

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// MAIN APP
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
export default function FuelPlanPro() {
  const [consented, setConsented] = useState(Compliance.hasValidConsent);
  const [step, setStep] = useState("profile");
  const [profile, setProfile] = useState({ name: "", age: "", weight: "", height: "", gender: "male", ethnicity: "", goal: "", budget: "moderate" });
  const [healthBase64, setHB64] = useState(null);
  const [healthFile, setHFile] = useState(null);
  const [macros, setMacros] = useState(null);
  const [micros, setMicros] = useState(null);
  const [safetyWarnings, setSW] = useState([]);
  const [mealPlan, setMealPlan] = useState(null);
  const [deals, setDeals] = useState([]);
  const [groceryList, setGrocery] = useState([]);
  const [checked, setChecked] = useState({});
  const [locationLabel, setLocLbl] = useState("");
  const [tab, setTab] = useState("plan");
  const [activeDay, setActiveDay] = useState(0);
  const [expanded, setExpanded] = useState(null);
  const [aiInsight, setAiInsight] = useState("");
  const [loading, setLoading] = useState({ macros: false, plan: false, deals: false });
  const [chatOpen, setChatOpen] = useState(false);
  const [chatHistory, setCH] = useState([]);
  const [chatInput, setChatInput] = useState("");
  const [chatLoading, setCL] = useState(false);
  const chatEndRef = useRef(null);
  const fileRef = useRef(null);

  useEffect(() => {
    const saved = Privacy.load();
    if (saved) {
      setProfile(p => ({ ...p, ...saved, name: saved.displayName }));
      const m = Privacy.loadData("fp_macros");
      const pl = Privacy.loadData("fp_mealplan");
      if (m) setMacros(m);
      if (pl) { setMealPlan(pl); const ings = new Set(); pl.forEach(d => Object.values(d.meals).forEach(meal => meal.ingredients?.forEach(i => ings.add(i)))); setGrocery([...ings]); }
      if (m && pl) setStep("plan");
    }
  }, []);

  const eth = () => ETHNICITIES.find(e => e.id === profile.ethnicity);
  const buildSystem = () => {
    const ctx = Privacy.buildAPIContext(profile, macros);
    return `User context (anonymized — no PII): Age bracket: ${ctx.ageBracket}, BMI category: ${ctx.bmiCategory}, Gender: ${ctx.gender}, Heritage: ${ETHNICITIES.find(e => e.id === ctx.ethnicity)?.label || "not set"}, Goal: ${ctx.goal}, Budget: ${ctx.budget}. Staples: ${eth()?.staples?.join(", ") || "general"}. ${ctx.macros ? `Macro targets: ${ctx.macros}.` : ""} Be warm, concise, culturally-aware, and always safety-conscious.`;
  };

  const getLocation = () => {
    navigator.geolocation?.getCurrentPosition(async pos => {
      try {
        const r = await fetch(`https://nominatim.openstreetmap.org/reverse?lat=${pos.coords.latitude}&lon=${pos.coords.longitude}&format=json`);
        const d = await r.json();
        const city = d.address?.city || d.address?.town || d.address?.suburb || "";
        const state = d.address?.state_code || "";
        setLocLbl(`${city}${city && state ? ", " : ""}${state}`);
        Compliance.auditLog("location_resolved", "city-level only, coords discarded");
      } catch { setLocLbl("Your Area"); }
    });
  };

  const handleFile = e => {
    const f = e.target.files[0]; if (!f) return;
    setHFile(f);
    const reader = new FileReader();
    reader.onload = ev => { setHB64(ev.target.result.split(",")[1]); Compliance.auditLog("health_report_loaded", "session-only, not stored"); };
    reader.readAsDataURL(f);
  };

  const analyzeMacros = useCallback(async () => {
    setLoading(l => ({ ...l, macros: true }));
    Privacy.recordAnalytic("goal", profile.goal);
    Privacy.recordAnalytic("ethnicity", profile.ethnicity);
    Compliance.auditLog("macros_requested", `goal:${profile.goal}`);
    const sys = `Expert sports dietitian. Return ONLY valid JSON.`;
    let msgs;
    if (healthBase64) {
      msgs = [{ role: "user", content: [{ type: "document", source: { type: "base64", media_type: "application/pdf", data: healthBase64 } }, { type: "text", text: `Analyze this health report. Anonymized profile: age bracket ${Privacy.anonymize(profile).ageBracket}, ${Privacy.anonymize(profile).bmiCategory} BMI, ${profile.gender}, goal: ${profile.goal}, heritage: ${eth()?.label}, staples: ${eth()?.staples?.join(", ")}. Return JSON: {"macros":{"calories":number,"protein_g":number,"carbs_g":number,"fat_g":number,"fiber_g":number},"micros":[{"name":string,"target":string,"reason":string,"foods":[string]}],"insights":[string],"warnings":[string],"ethnicity_note":string}` }] }];
    } else {
      const ap = Privacy.anonymize(profile);
      const estW = ap.bmiCategory === "underweight" ? 55 : ap.bmiCategory === "overweight" ? 85 : ap.bmiCategory === "obese" ? 105 : 70;
      const midAge = profile.age < 25 ? 22 : profile.age < 35 ? 30 : profile.age < 45 ? 40 : profile.age < 55 ? 50 : 60;
      msgs = [{ role: "user", content: `Calculate macros. Approximate profile: ~${midAge}yo, ~${estW}kg estimated, ${profile.gender}, goal: ${profile.goal}, heritage: ${eth()?.label}, budget: ${profile.budget}, staples: ${eth()?.staples?.join(", ")}. Return JSON: {"macros":{"calories":number,"protein_g":number,"carbs_g":number,"fat_g":number,"fiber_g":number},"micros":[{"name":string,"target":string,"reason":string,"foods":[string]}],"insights":[string],"warnings":[],"ethnicity_note":string}` }];
    }
    const data = await callJSON(msgs, sys);
    if (data?.macros) {
      const v = Safety.validateMacros(data.macros, profile.weight || 70);
      setMacros(v.macros); setMicros(data); setSW(v.warnings);
      Privacy.saveData("fp_macros", v.macros);
      Compliance.auditLog("macros_set", `cal:${v.macros.calories}`);
    }
    setLoading(l => ({ ...l, macros: false }));
    return data;
  }, [profile, healthBase64]);

  const generatePlan = useCallback(async (macroData) => {
    const m = macroData?.macros || macros; if (!m) return;
    setLoading(l => ({ ...l, plan: true }));
    Compliance.auditLog("plan_generated", `heritage:${profile.ethnicity},goal:${profile.goal}`);
    const data = await callJSON([{ role: "user", content: `3-day ${profile.goal} meal plan for ${eth()?.label} heritage. Macros/day: ${m.calories}cal, ${m.protein_g}g P, ${m.carbs_g}g C, ${m.fat_g}g F. Staples: ${eth()?.staples?.join(", ")}. Return JSON: {"days":[{"day":"Monday","meals":{"breakfast":{"name":string,"description":string,"cals":number,"protein":number,"carbs":number,"fat":number,"ingredients":[string]},"lunch":same,"dinner":same,"snack":same}}]} for 3 days.` }], `World-class ${eth()?.label} cuisine nutritionist. Return ONLY valid JSON.`);
    if (data?.days) {
      setMealPlan(data.days); Privacy.saveData("fp_mealplan", data.days);
      const ings = new Set(); data.days.forEach(d => Object.values(d.meals).forEach(meal => meal.ingredients?.forEach(i => ings.add(i)))); setGrocery([...ings]);
    }
    setLoading(l => ({ ...l, plan: false }));
  }, [macros, profile]);

  const fetchDeals = useCallback(async () => {
    setLoading(l => ({ ...l, deals: true })); getLocation();
    Compliance.auditLog("deals_searched", `location:${locationLabel || "unknown"}`);
    const loc = locationLabel || "United States";
    const raw = await callClaude([{ role: "user", content: `Current grocery deals near ${loc} for: ${groceryList.slice(0, 8).join(", ")}. Also stores with ${eth()?.label} foods near ${loc}. Return JSON array of 7 deals: [{"store":string,"item":string,"price":string,"savings":string,"tag":string,"tip":string,"category":"protein"|"produce"|"pantry"|"specialty"}]` }], `Grocery deals expert. Return ONLY valid JSON array.`, true);
    try { const m = raw.replace(/```json|```/g, "").trim().match(/\[[\s\S]*\]/); if (m) setDeals(JSON.parse(m[0])); else setDeals(fallbackDeals()); } catch { setDeals(fallbackDeals()); }
    setLoading(l => ({ ...l, deals: false }));
  }, [groceryList, locationLabel, profile.ethnicity]);

  const fallbackDeals = () => [
    { store: "Walmart", item: `${eth()?.staples?.[0] || "Chicken breast"} (2lb)`, price: "$6.98", savings: "Save 18%", tag: "Best Value", tip: "Check international aisle", category: "protein" },
    { store: "Trader Joe's", item: "Organic lentils (1lb)", price: "$1.99", savings: "Save 30%", tag: "Staple", tip: "High-fiber plant protein", category: "pantry" },
    { store: "Costco", item: "Wild Salmon (3lb)", price: "$19.99", savings: "Save 35%", tag: "Bulk Deal", tip: "Portion and freeze same day", category: "protein" },
    { store: "H Mart / International Market", item: `${eth()?.label} specialty ingredients`, price: "$4.49", savings: "Save 40%", tag: "Ethnic Pick", tip: "Best authentic source", category: "specialty" },
  ];

  useEffect(() => {
    if (tab === "plan" && mealPlan) {
      callClaude([{ role: "user", content: `One sharp motivating nutrition tip for day ${activeDay + 1} ${eth()?.label} meals (goal: ${profile.goal}). Under 28 words, no bullets.` }], buildSystem()).then(t => setAiInsight(t.trim()));
    }
  }, [tab, activeDay, mealPlan]);

  const startPlan = async () => {
    Privacy.save(profile);
    Compliance.auditLog("plan_started", `goal:${profile.goal},heritage:${profile.ethnicity}`);
    setStep("plan"); setTab("plan");
    const data = await analyzeMacros();
    await generatePlan(data);
    const greeting = await callClaude([{ role: "user", content: `Warm 2-sentence welcome for new ${eth()?.label} ${profile.goal} plan. Mention one cultural staple food. Under 35 words. No personal identifiers.` }], buildSystem());
    setCH([{ role: "assistant", content: greeting.trim(), chips: ["What to eat first?", "Swap a meal", "Explain my macros", "Find deals near me", "Snack ideas"] }]);
    setChatOpen(true);
  };

  const sendChat = useCallback(async (text) => {
    if (!text.trim() || chatLoading) return;
    const screen = Safety.screenMessage(text);
    Compliance.auditLog("chat_message", `type:${screen.type}`);
    if (screen.block) { setCH(h => [...h, { role: "user", content: text }, { role: "assistant", content: "🚨 This sounds like a medical emergency. Please call 911 or your local emergency services immediately.", type: "emergency" }]); return; }
    const apiHist = [...chatHistory.map(m => ({ role: m.role, content: m.content })), { role: "user", content: text.trim() }];
    setCH(h => [...h, { role: "user", content: text.trim() }]); setChatInput(""); setCL(true);
    let sysAdd = "";
    if (screen.type === "diagnosis") sysAdd = "User is asking for a medical diagnosis. Firmly but compassionately decline and direct them to a qualified physician or registered dietitian.";
    if (screen.type === "ed_risk") sysAdd = "User may be showing signs of disordered eating. Respond with warmth and compassion. Provide the NEDA helpline.";
    if (screen.type === "minor_mention") sysAdd = "If user is asking about nutrition for a child, remind them that pediatric nutrition requires a pediatric dietitian.";
    const lower = text.toLowerCase(); let reply = "";
    if ((lower.includes("swap") || lower.includes("replace")) && mealPlan) {
      const sw = await callJSON([{ role: "user", content: `User: "${text}". ${eth()?.label} plan. Goal: ${profile.goal}. 1 culturally-appropriate swap. JSON: {"original":string,"name":string,"cals":number,"protein":number,"carbs":number,"fat":number,"ingredients":[string],"reason":string}` }], buildSystem() + "\n" + sysAdd);
      reply = sw ? `Great swap idea!\n\n🔄 Replace: ${sw.original}\n✅ With: ${sw.name}\n\n${sw.reason}\n\nMacros: ${sw.cals} cal · ${sw.protein}g protein · ${sw.carbs}g carbs\nIngredients: ${sw.ingredients?.join(", ")}\n\n⚕️ Verify this fits your individual health needs with a dietitian.` : await callClaude(apiHist, buildSystem() + "\n" + sysAdd);
    } else if ((lower.includes("deal") || lower.includes("shop") || lower.includes("buy")) && deals.length === 0) {
      await fetchDeals(); reply = `I've searched for current grocery deals! Check the 🛒 Deals tab for real-time prices on your plan's ingredients near you.`;
    } else { reply = await callClaude(apiHist, buildSystem() + "\n" + sysAdd); }
    const chips = (lower.includes("swap") || lower.includes("replace")) ? ["Another swap", "Vegetarian option", "Show grocery list"] : ["Tell me more", "Adjust my plan", "Recipe ideas", "Shopping tips"];
    setCH(h => [...h, { role: "assistant", content: reply.trim(), chips, type: screen.type !== "safe" ? screen.type : undefined }]); setCL(false);
  }, [chatHistory, chatLoading, mealPlan, deals, profile, macros, fetchDeals]);

  useEffect(() => { chatEndRef.current?.scrollIntoView({ behavior: "smooth" }); }, [chatHistory, chatLoading]);

  const dayTotals = d => d ? Object.values(d.meals).reduce((a, m) => ({ cals: a.cals + (m.cals || 0), protein: a.protein + (m.protein || 0), carbs: a.carbs + (m.carbs || 0), fat: a.fat + (m.fat || 0) }), { cals: 0, protein: 0, carbs: 0, fat: 0 }) : {};
  const catColor = { protein: G, produce: "#a8e063", pantry: A, specialty: P };
  const handleDeleteData = () => { if (window.confirm("Delete all your data? This cannot be undone.")) { Compliance.revokeConsent(); setConsented(false); setStep("profile"); setMacros(null); setMealPlan(null); setGrocery([]); } };

  if (!consented) return (
    <><style>{css}</style>
      <ConsentScreen
        onAccept={() => { Compliance.recordConsent(true); Compliance.auditLog("consent_accepted", `tos:${LEGAL.TOS_VERSION}`); setConsented(true); }}
        onDecline={() => { window.alert("You must accept the Terms of Service and Privacy Policy to use FuelPlan Pro."); }}
      /></>
  );

  return (
    <div style={{ minHeight: "100vh", background: "#07080f", color: "#eef0f5" }}>
      <style>{css}</style>

      {/* ━━ PROFILE STEP ━━ */}
      {step === "profile" && (
        <div style={{ minHeight: "100vh", display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", padding: "40px 16px", background: `radial-gradient(ellipse 100% 50% at 50% -10%, ${G}10 0%, transparent 70%)` }}>
          <div style={{ fontSize: 10, fontWeight: 700, letterSpacing: 3, textTransform: "uppercase", color: G, marginBottom: 10 }}>FUELPLAN PRO</div>
          <h1 style={{ fontFamily: "'Syne',sans-serif", fontSize: "clamp(32px,6vw,60px)", fontWeight: 800, textAlign: "center", lineHeight: .95, marginBottom: 10 }}>YOUR HERITAGE.<br /><span style={{ color: G }}>YOUR HEALTH.</span><br />YOUR FOOD.</h1>
          <div style={{ display: "flex", gap: 8, marginBottom: 32, flexWrap: "wrap", justifyContent: "center" }}>
            <div style={{ background: `${G}10`, border: `1px solid ${G}25`, borderRadius: 8, padding: "5px 12px", fontSize: 11, color: G, fontWeight: 700 }}>🔒 Privacy First</div>
            <div style={{ background: "rgba(255,107,107,.08)", border: "1px solid rgba(255,107,107,.2)", borderRadius: 8, padding: "5px 12px", fontSize: 11, color: R, fontWeight: 700 }}>⚕️ Not Medical Advice</div>
            <div style={{ background: `${B}10`, border: `1px solid ${B}25`, borderRadius: 8, padding: "5px 12px", fontSize: 11, color: B, fontWeight: 700 }}>✅ GDPR/CCPA Compliant</div>
          </div>
          <div style={{ width: "100%", maxWidth: 520, background: "rgba(255,255,255,.025)", border: "1px solid rgba(255,255,255,.08)", borderRadius: 24, padding: 28 }}>
            <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12, marginBottom: 20 }}>
              {[["Name", "name", "text", "First name"], ["Age", "age", "number", "Years"], ["Weight (kg)", "weight", "number", "kg"], ["Height (cm)", "height", "number", "cm"]].map(([lb, k, t, ph]) => (
                <div key={k}><div style={{ fontSize: 10, fontWeight: 700, letterSpacing: 2, textTransform: "uppercase", color: "rgba(255,255,255,.3)", marginBottom: 6 }}>{lb}</div><input type={t} placeholder={ph} value={profile[k]} onChange={e => setProfile(p => ({ ...p, [k]: e.target.value }))} style={{ width: "100%", background: "rgba(255,255,255,.05)", border: "1px solid rgba(255,255,255,.1)", borderRadius: 10, padding: "10px 14px", color: "#eef0f5", fontFamily: "'DM Sans',sans-serif", fontSize: 14 }} /></div>
              ))}
            </div>
            <div style={{ marginBottom: 18 }}><div style={{ fontSize: 10, fontWeight: 700, letterSpacing: 2, textTransform: "uppercase", color: "rgba(255,255,255,.3)", marginBottom: 8 }}>Biological Sex</div><div style={{ display: "flex", gap: 8 }}>{["male", "female", "other"].map(g => <Pill key={g} active={profile.gender === g} onClick={() => setProfile(p => ({ ...p, gender: g }))} color={G}>{g.charAt(0).toUpperCase() + g.slice(1)}</Pill>)}</div></div>
            <div style={{ marginBottom: 18 }}><div style={{ fontSize: 10, fontWeight: 700, letterSpacing: 2, textTransform: "uppercase", color: "rgba(255,255,255,.3)", marginBottom: 8 }}>Cultural Heritage</div>
              <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8 }}>{ETHNICITIES.map(e => <button key={e.id} onClick={() => setProfile(p => ({ ...p, ethnicity: e.id }))} style={{ padding: "10px 14px", borderRadius: 12, border: `1px solid ${profile.ethnicity === e.id ? G : "rgba(255,255,255,.08)"}`, background: profile.ethnicity === e.id ? `${G}12` : "transparent", color: profile.ethnicity === e.id ? G : "rgba(255,255,255,.55)", fontFamily: "'DM Sans',sans-serif", fontSize: 13, fontWeight: 500, cursor: "pointer", display: "flex", alignItems: "center", gap: 8, transition: "all .2s" }}><span>{e.emoji}</span><span>{e.label}</span></button>)}</div>
            </div>
            <div style={{ marginBottom: 18 }}><div style={{ fontSize: 10, fontWeight: 700, letterSpacing: 2, textTransform: "uppercase", color: "rgba(255,255,255,.3)", marginBottom: 8 }}>Primary Goal</div><div style={{ display: "flex", flexWrap: "wrap", gap: 8 }}>{GOALS.map(g => <Pill key={g} active={profile.goal === g} onClick={() => setProfile(p => ({ ...p, goal: g }))} color={A}>{g}</Pill>)}</div></div>
            <div onClick={() => fileRef.current?.click()} style={{ border: `2px dashed ${healthFile ? B : "rgba(255,255,255,.1)"}`, borderRadius: 14, padding: "16px", textAlign: "center", cursor: "pointer", background: healthFile ? `${B}08` : "transparent", marginBottom: 18, transition: "all .3s" }}>
              <div style={{ fontSize: 20, marginBottom: 4 }}>{healthFile ? "📄" : "📋"}</div>
              <div style={{ fontSize: 13, fontWeight: 600, color: healthFile ? B : "rgba(255,255,255,.4)", marginBottom: 2 }}>{healthFile ? healthFile.name : "Upload Health Report (optional)"}</div>
              <div style={{ fontSize: 11, color: "rgba(255,255,255,.28)" }}>Session-only · Never stored · Discarded after analysis</div>
              <input ref={fileRef} type="file" accept=".pdf,image/*" style={{ display: "none" }} onChange={handleFile} />
            </div>
            <button onClick={startPlan} style={{ width: "100%", padding: 14, borderRadius: 12, border: "none", background: profile.ethnicity && profile.goal && profile.age ? G : "rgba(255,255,255,.08)", color: profile.ethnicity && profile.goal && profile.age ? "#07080f" : "rgba(255,255,255,.3)", fontFamily: "'Syne',sans-serif", fontSize: 16, fontWeight: 700, letterSpacing: 1, cursor: profile.ethnicity && profile.goal && profile.age ? "pointer" : "not-allowed", transition: "all .2s" }}>BUILD MY PLAN →</button>
            <MedDisclaimer compact />
          </div>
        </div>
      )}

      {/* ━━ PLAN STEP ━━ */}
      {step === "plan" && (
        <div style={{ minHeight: "100vh", display: "flex", flexDirection: "column" }}>
          <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", padding: "12px 16px", borderBottom: "1px solid rgba(255,255,255,.06)", position: "sticky", top: 0, zIndex: 30, background: "rgba(7,8,15,.93)", backdropFilter: "blur(20px)" }}>
            <div style={{ fontFamily: "'Syne',sans-serif", fontSize: 17, fontWeight: 800 }}>FUEL<span style={{ color: G }}>PLAN</span><span style={{ fontSize: 10, background: `${G}20`, color: G, border: `1px solid ${G}30`, padding: "2px 7px", borderRadius: 20, marginLeft: 7, letterSpacing: 1 }}>PRO</span></div>
            <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
              {locationLabel && <div style={{ fontSize: 11, color: "rgba(255,255,255,.35)" }}>📍 {locationLabel}</div>}
              <div style={{ fontSize: 10, background: `${G}10`, border: `1px solid ${G}25`, borderRadius: 8, padding: "4px 10px", color: G, fontWeight: 700 }}>🔒 Private</div>
              <div style={{ fontSize: 10, background: "rgba(255,107,107,.08)", border: "1px solid rgba(255,107,107,.2)", borderRadius: 8, padding: "4px 10px", color: R, fontWeight: 700 }}>⚕️ Not medical advice</div>
            </div>
          </div>

          <div style={{ display: "flex", gap: 3, padding: "10px 12px", background: "rgba(255,255,255,.015)", borderBottom: "1px solid rgba(255,255,255,.05)", overflowX: "auto" }}>
            {[["plan", "🍽️ Plan"], ["macros", "📊 Macros"], ["deals", "🛒 Deals"], ["grocery", "📋 List"], ["compliance", "🔒 Privacy"]].map(([id, label]) => (
              <button key={id} onClick={() => { setTab(id); if (id === "deals" && deals.length === 0) fetchDeals(); }} style={{ flexShrink: 0, padding: "8px 13px", borderRadius: 8, border: "none", background: tab === id ? G : "transparent", color: tab === id ? "#07080f" : "rgba(255,255,255,.4)", fontFamily: "'DM Sans',sans-serif", fontSize: 12, fontWeight: 700, cursor: "pointer", transition: "all .2s" }}>{label}</button>
            ))}
          </div>

          <div style={{ flex: 1, padding: "18px 14px", maxWidth: 640, margin: "0 auto", width: "100%", paddingBottom: 110 }}>
            {tab === "plan" && (
              <>
                {loading.plan || loading.macros ? <Spinner label="Building your culturally-rooted meal plan…" /> : (
                  <>
                    <MedDisclaimer />
                    <SafetyBanner warnings={safetyWarnings} />
                    {aiInsight && <div style={{ background: `${G}0a`, border: `1px solid ${G}20`, borderRadius: 14, padding: "13px 16px", marginBottom: 16, display: "flex", gap: 10 }}><span style={{ fontSize: 16 }}>⚡</span><div><div style={{ fontSize: 10, fontWeight: 700, letterSpacing: 2, textTransform: "uppercase", color: G, marginBottom: 4 }}>AI Coach · General Guidance Only</div><div style={{ fontSize: 13, color: "rgba(255,255,255,.75)", lineHeight: 1.6 }}>{aiInsight}</div><div style={{ fontSize: 10, color: "rgba(255,255,255,.25)", marginTop: 4 }}>AI-generated · Not a substitute for professional dietary advice</div></div></div>}
                    {mealPlan && <div style={{ display: "flex", gap: 8, marginBottom: 16, overflowX: "auto" }}>{mealPlan.map((d, i) => <button key={i} onClick={() => setActiveDay(i)} style={{ flexShrink: 0, padding: "7px 16px", borderRadius: 8, border: `1px solid ${activeDay === i ? G : "rgba(255,255,255,.08)"}`, background: activeDay === i ? `${G}15` : "transparent", color: activeDay === i ? G : "rgba(255,255,255,.5)", fontFamily: "'DM Sans',sans-serif", fontSize: 13, fontWeight: 600, cursor: "pointer" }}>{d.day}</button>)}</div>}
                    {mealPlan && (() => { const t = dayTotals(mealPlan[activeDay]); return (<Card style={{ marginBottom: 16, display: "grid", gridTemplateColumns: "repeat(4,1fr)", gap: 8, textAlign: "center" }}>{[["Calories", t.cals, A, ""], ["Protein", t.protein, G, "g"], ["Carbs", t.carbs, B, "g"], ["Fat", t.fat, "#ff6b9d", "g"]].map(([l, v, c, u]) => <div key={l}><div style={{ fontFamily: "'Syne',sans-serif", fontSize: 20, fontWeight: 700, color: c }}>{v}{u}</div><div style={{ fontSize: 10, color: "rgba(255,255,255,.3)", textTransform: "uppercase", letterSpacing: 1 }}>{l}</div></div>)}</Card>); })()}
                    {mealPlan && Object.entries(mealPlan[activeDay].meals).map(([type, meal]) => {
                      const accMap = { breakfast: A, lunch: B, dinner: G, snack: P }; const acc = accMap[type] || G; const key = `${activeDay}-${type}`;
                      return (<div key={type} style={{ marginBottom: 10 }}><div onClick={() => setExpanded(expanded === key ? null : key)} style={{ background: "rgba(255,255,255,.03)", border: "1px solid rgba(255,255,255,.07)", borderRadius: 16, padding: "15px 16px", cursor: "pointer", borderLeft: `3px solid ${acc}` }}><div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start" }}><div style={{ flex: 1 }}><div style={{ fontSize: 10, fontWeight: 700, letterSpacing: 2, textTransform: "uppercase", color: "rgba(255,255,255,.3)", marginBottom: 4 }}>{type}</div><div style={{ fontSize: 15, fontWeight: 600, marginBottom: 4 }}>{meal.name}</div>{meal.description && <div style={{ fontSize: 12, color: "rgba(255,255,255,.4)", lineHeight: 1.5, marginBottom: 7 }}>{meal.description}</div>}<div style={{ display: "flex", gap: 12, flexWrap: "wrap" }}>{[["🔥", meal.cals, "cal"], ["💪", meal.protein, "g P"], ["🌾", meal.carbs, "g C"], ["🥑", meal.fat, "g F"]].map(([ic, v, u]) => <span key={u} style={{ fontSize: 12, color: "rgba(255,255,255,.45)" }}>{ic} <strong style={{ color: "rgba(255,255,255,.8)" }}>{v}</strong>{u}</span>)}</div></div><span style={{ color: "rgba(255,255,255,.3)", fontSize: 16, marginLeft: 10 }}>{expanded === key ? "▲" : "▼"}</span></div>{expanded === key && <div style={{ marginTop: 14, paddingTop: 14, borderTop: "1px solid rgba(255,255,255,.06)" }}><div style={{ fontSize: 10, fontWeight: 700, letterSpacing: 1.5, textTransform: "uppercase", color: "rgba(255,255,255,.3)", marginBottom: 8 }}>Ingredients</div><div style={{ display: "flex", flexWrap: "wrap", gap: 6 }}>{meal.ingredients?.map(ing => <span key={ing} style={{ fontSize: 12, background: "rgba(255,255,255,.05)", border: "1px solid rgba(255,255,255,.1)", color: "rgba(255,255,255,.65)", padding: "4px 10px", borderRadius: 20 }}>{ing}</span>)}</div></div>}</div></div>);
                    })}
                  </>
                )}
              </>
            )}

            {tab === "macros" && (
              <>
                {loading.macros ? <Spinner label="Analyzing…" /> : macros ? (
                  <>
                    <SafetyBanner warnings={safetyWarnings} />
                    <MedDisclaimer />
                    <Card style={{ marginBottom: 14 }} glow={G}>
                      <div style={{ fontSize: 10, fontWeight: 700, letterSpacing: 2, textTransform: "uppercase", color: "rgba(255,255,255,.3)", marginBottom: 14 }}>Daily Macro Targets</div>
                      <div style={{ display: "grid", gridTemplateColumns: "repeat(2,1fr)", gap: 10 }}>
                        {[["🔥 Calories", macros.calories, "", A], ["💪 Protein", macros.protein_g, "g", G], ["🌾 Carbs", macros.carbs_g, "g", B], ["🥑 Fat", macros.fat_g, "g", "#ff6b9d"]].map(([l, v, u, c]) => <div key={l} style={{ background: `${c}0a`, border: `1px solid ${c}20`, borderRadius: 12, padding: "14px 16px" }}><div style={{ fontSize: 11, color: "rgba(255,255,255,.4)", marginBottom: 4 }}>{l}</div><div style={{ fontFamily: "'Syne',sans-serif", fontSize: 26, fontWeight: 700, color: c }}>{v}<span style={{ fontSize: 13 }}>{u}</span></div></div>)}
                      </div>
                      <div style={{ marginTop: 12, paddingTop: 12, borderTop: "1px solid rgba(255,255,255,.06)", fontSize: 13, color: "rgba(255,255,255,.5)" }}>🌿 Fiber: <strong style={{ color: "rgba(255,255,255,.85)" }}>{macros.fiber_g}g/day</strong></div>
                      <div style={{ fontSize: 11, color: "rgba(255,255,255,.25)", marginTop: 8 }}>Calculated using Mifflin-St Jeor BMR formula with AMDR macronutrient ranges. Verify with a registered dietitian.</div>
                    </Card>
                    {micros?.ethnicity_note && <Card style={{ marginBottom: 14, background: `${A}07`, borderColor: `${A}20` }}><div style={{ display: "flex", gap: 12 }}><span style={{ fontSize: 22 }}>{eth()?.emoji}</span><div><div style={{ fontSize: 10, fontWeight: 700, letterSpacing: 2, textTransform: "uppercase", color: A, marginBottom: 5 }}>Cultural Nutrition Note</div><div style={{ fontSize: 13, color: "rgba(255,255,255,.7)", lineHeight: 1.6 }}>{micros.ethnicity_note}</div></div></div></Card>}
                    <div style={{ fontSize: 10, fontWeight: 700, letterSpacing: 2, textTransform: "uppercase", color: "rgba(255,255,255,.3)", marginBottom: 10 }}>Key Micronutrients</div>
                    {micros?.micros?.map((m, i) => <Card key={i} style={{ marginBottom: 10 }}><div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 6 }}><div style={{ fontWeight: 600, fontSize: 15 }}>{m.name}</div><Tag color={B}>{m.target}</Tag></div><div style={{ fontSize: 12, color: "rgba(255,255,255,.5)", lineHeight: 1.5, marginBottom: 8 }}>{m.reason}</div><div style={{ display: "flex", flexWrap: "wrap", gap: 6 }}>{m.foods?.map(f => <span key={f} style={{ fontSize: 11, background: `${G}10`, border: `1px solid ${G}20`, color: G, padding: "3px 9px", borderRadius: 20 }}>{f}</span>)}</div></Card>)}
                  </>
                ) : <Spinner label="Calculating…" />}
              </>
            )}

            {tab === "deals" && (
              <>
                <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 6 }}><div style={{ fontFamily: "'Syne',sans-serif", fontSize: 24, fontWeight: 800 }}>LIVE DEALS</div><button onClick={fetchDeals} style={{ background: `${G}18`, border: `1px solid ${G}30`, color: G, borderRadius: 8, padding: "6px 14px", fontSize: 12, fontWeight: 700, cursor: "pointer" }}>🔄 Refresh</button></div>
                <div style={{ fontSize: 13, color: "rgba(255,255,255,.4)", marginBottom: 18 }}>{locationLabel ? `Near ${locationLabel} (city-level only, coords discarded)` : "Deals for your plan ingredients"}</div>
                {loading.deals ? <Spinner label="Searching deals…" /> : deals.map((d, i) => (
                  <Card key={i} style={{ marginBottom: 10, display: "flex", gap: 14, alignItems: "flex-start" }}>
                    <div style={{ width: 44, height: 44, borderRadius: 12, background: `${catColor[d.category] || G}15`, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 20, flexShrink: 0 }}>{d.category === "protein" ? "🥩" : d.category === "produce" ? "🥦" : d.category === "specialty" ? "🌏" : "🥫"}</div>
                    <div style={{ flex: 1 }}><div style={{ fontSize: 10, fontWeight: 700, letterSpacing: 1.5, textTransform: "uppercase", color: "rgba(255,255,255,.3)", marginBottom: 2 }}>{d.store}</div><div style={{ fontWeight: 600, fontSize: 14, marginBottom: 5 }}>{d.item}</div><Tag color={catColor[d.category] || G}>{d.tag}</Tag><div style={{ display: "flex", gap: 10, alignItems: "center", margin: "7px 0" }}><span style={{ fontFamily: "'Syne',sans-serif", fontSize: 22, fontWeight: 700, color: A }}>{d.price}</span><span style={{ fontSize: 11, fontWeight: 700, background: "rgba(80,220,120,.1)", color: "#50dc78", border: "1px solid rgba(80,220,120,.2)", padding: "2px 8px", borderRadius: 20 }}>{d.savings}</span></div><div style={{ fontSize: 12, color: "rgba(255,255,255,.4)", lineHeight: 1.5 }}>💡 {d.tip}</div></div>
                  </Card>
                ))}
              </>
            )}

            {tab === "grocery" && (
              <>
                <div style={{ fontFamily: "'Syne',sans-serif", fontSize: 24, fontWeight: 800, marginBottom: 6 }}>GROCERY LIST</div>
                <div style={{ fontSize: 13, color: "rgba(255,255,255,.4)", marginBottom: 18 }}>Stored locally on your device only</div>
                <div style={{ marginBottom: 20 }}><div style={{ display: "flex", justifyContent: "space-between", fontSize: 12, color: "rgba(255,255,255,.4)", marginBottom: 8 }}><span>Progress</span><span style={{ color: G }}>{Object.values(checked).filter(Boolean).length}/{groceryList.length} items</span></div><div style={{ height: 4, background: "rgba(255,255,255,.08)", borderRadius: 4 }}><div style={{ height: "100%", background: G, borderRadius: 4, width: `${groceryList.length ? (Object.values(checked).filter(Boolean).length / groceryList.length) * 100 : 0}%`, transition: "width .4s" }} /></div></div>
                {groceryList.map(item => <div key={item} onClick={() => setChecked(c => ({ ...c, [item]: !c[item] }))} style={{ display: "flex", alignItems: "center", gap: 12, padding: "12px 14px", borderRadius: 12, border: "1px solid rgba(255,255,255,.06)", background: "rgba(255,255,255,.02)", marginBottom: 8, cursor: "pointer", opacity: checked[item] ? .35 : 1, textDecoration: checked[item] ? "line-through" : "none", transition: "all .2s" }}><div style={{ width: 22, height: 22, borderRadius: 6, flexShrink: 0, display: "flex", alignItems: "center", justifyContent: "center", border: `2px solid ${checked[item] ? G : "rgba(255,255,255,.2)"}`, background: checked[item] ? G : "transparent", transition: "all .2s" }}>{checked[item] && <span style={{ color: "#07080f", fontSize: 12, fontWeight: 700 }}>✓</span>}</div><span style={{ fontSize: 14, fontWeight: 500 }}>{item}</span></div>)}
              </>
            )}

            {tab === "compliance" && <CompliancePanel onDeleteData={handleDeleteData} />}
          </div>

          {/* Chat FAB */}
          <button onClick={() => setChatOpen(o => !o)} style={{ position: "fixed", bottom: 26, right: 22, width: 56, height: 56, borderRadius: "50%", border: "none", cursor: "pointer", zIndex: 50, background: chatOpen ? "rgba(255,255,255,.1)" : G, color: chatOpen ? "rgba(255,255,255,.8)" : "#07080f", fontSize: 22, display: "flex", alignItems: "center", justifyContent: "center", boxShadow: chatOpen ? "none" : `0 0 0 0 ${G}88`, animation: chatOpen ? "none" : "pulse 2.5s infinite", transition: "all .3s cubic-bezier(.22,1,.36,1)" }}>
            {chatOpen ? "✕" : "⚡"}
          </button>

          {/* Chat Panel */}
          {chatOpen && (
            <div style={{ position: "fixed", bottom: 96, right: 14, left: 14, maxWidth: 480, margin: "0 auto", height: "66vh", maxHeight: 540, background: "rgba(9,10,18,.97)", border: "1px solid rgba(255,255,255,.1)", borderRadius: 24, zIndex: 49, display: "flex", flexDirection: "column", boxShadow: `0 30px 80px rgba(0,0,0,.7), 0 0 0 1px ${G}18`, overflow: "hidden", animation: "slideUp .35s cubic-bezier(.22,1,.36,1)" }}>
              <div style={{ padding: "13px 16px", borderBottom: "1px solid rgba(255,255,255,.07)", display: "flex", alignItems: "center", gap: 10, background: "rgba(255,255,255,.02)" }}>
                <div style={{ width: 34, height: 34, borderRadius: "50%", background: `${G}20`, border: `1px solid ${G}40`, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 15 }}>⚡</div>
                <div style={{ flex: 1 }}><div style={{ fontFamily: "'Syne',sans-serif", fontSize: 14, fontWeight: 700 }}>FuelCoach AI</div><div style={{ fontSize: 10, color: G, display: "flex", alignItems: "center", gap: 4 }}><span style={{ width: 5, height: 5, borderRadius: "50%", background: G, display: "inline-block" }} /> Safety-screened · No PII sent · Not medical advice</div></div>
              </div>
              <div style={{ flex: 1, overflowY: "auto", padding: "14px 12px 8px", display: "flex", flexDirection: "column" }}>
                {chatHistory.length === 0 && !chatLoading && <div style={{ textAlign: "center", color: "rgba(255,255,255,.3)", fontSize: 13, margin: "auto" }}><div style={{ fontSize: 30, marginBottom: 8 }}>⚡</div>Ask about your plan, meals, macros, or deals!</div>}
                {chatHistory.map((msg, i) => <ChatBubble key={i} msg={msg} onChip={text => sendChat(text)} />)}
                {chatLoading && <div style={{ display: "flex", gap: 10, alignItems: "center", marginBottom: 10 }}><div style={{ width: 30, height: 30, borderRadius: "50%", background: `${G}20`, border: `1px solid ${G}40`, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 14, flexShrink: 0 }}>⚡</div><div style={{ display: "flex", gap: 5, padding: "11px 14px", background: "rgba(255,255,255,.05)", border: "1px solid rgba(255,255,255,.1)", borderRadius: "4px 16px 16px 16px" }}>{[0, 1, 2].map(i => <div key={i} style={{ width: 6, height: 6, borderRadius: "50%", background: "rgba(255,255,255,.35)", animation: `bounce 1.2s ${i * .2}s infinite ease-in-out` }} />)}</div></div>}
                <div ref={chatEndRef} />
              </div>
              {chatHistory.length <= 1 && !chatLoading && <div style={{ padding: "0 12px 8px", display: "flex", gap: 6, overflowX: "auto" }}>{["Swap a dinner", "Best snack ideas", "Explain my macros", "Find deals near me", "Vegetarian options"].map(s => <button key={s} onClick={() => sendChat(s)} style={{ flexShrink: 0, padding: "5px 12px", borderRadius: 20, border: "1px solid rgba(255,255,255,.1)", background: "transparent", color: "rgba(255,255,255,.45)", fontFamily: "'DM Sans',sans-serif", fontSize: 11, fontWeight: 600, cursor: "pointer", whiteSpace: "nowrap" }}>{s}</button>)}</div>}
              <div style={{ padding: "10px 12px", borderTop: "1px solid rgba(255,255,255,.07)", display: "flex", gap: 8, alignItems: "flex-end" }}>
                <textarea value={chatInput} onChange={e => setChatInput(e.target.value)} onKeyDown={e => { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); sendChat(chatInput); } }} placeholder="Ask about your plan, swaps, deals…" rows={1} style={{ flex: 1, background: "rgba(255,255,255,.05)", border: "1px solid rgba(255,255,255,.1)", borderRadius: 12, padding: "9px 13px", color: "#eef0f5", fontFamily: "'DM Sans',sans-serif", fontSize: 13, resize: "none", maxHeight: 80, lineHeight: 1.5 }} />
                <button onClick={() => sendChat(chatInput)} disabled={!chatInput.trim() || chatLoading} style={{ width: 40, height: 40, borderRadius: 10, border: "none", background: chatInput.trim() && !chatLoading ? G : "rgba(255,255,255,.07)", color: chatInput.trim() && !chatLoading ? "#07080f" : "rgba(255,255,255,.3)", fontSize: 16, cursor: chatInput.trim() && !chatLoading ? "pointer" : "not-allowed", display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0, transition: "all .2s" }}>↑</button>
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
